runtime: python27
env: standard
threadsafe: true
instance_class: F1
handlers:
  - url: /
    application_readable: false
    static_files: www/index.html
    require_matching_file: false
    upload: www/index.html
  - url: '/(.*)'
    application_readable: false
    static_files: "www/\\1"
    require_matching_file: false
    upload: 'www/.*'
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic